object Form4: TForm4
  Left = 255
  Top = 132
  Caption = 'Form4'
  ClientHeight = 266
  ClientWidth = 493
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 40
    Top = 8
    Width = 425
    Height = 241
    Caption = 'Panel1'
    TabOrder = 0
    object BGRAShape1: TBGRAShape
      Left = 1
      Top = 1
      Width = 423
      Height = 239
      Align = alClient
      BorderColor = clWindowText
      BorderGradient.StartColor = clWhite
      BorderGradient.StartColorOpacity = 255
      BorderGradient.DrawMode = dmSet
      BorderGradient.EndColor = clBlack
      BorderGradient.EndColorOpacity = 255
      BorderGradient.ColorCorrection = True
      BorderGradient.GradientType = gtLinear
      BorderGradient.Point2XPercent = 100.000000000000000000
      BorderGradient.Point2YPercent = 100.000000000000000000
      BorderGradient.Sinus = False
      FillColor = clWindow
      FillOpacity = 255
      FillGradient.StartColor = clWhite
      FillGradient.StartColorOpacity = 255
      FillGradient.DrawMode = dmSet
      FillGradient.EndColor = clBlack
      FillGradient.EndColorOpacity = 255
      FillGradient.ColorCorrection = True
      FillGradient.GradientType = gtLinear
      FillGradient.Point2YPercent = 100.000000000000000000
      FillGradient.Sinus = False
      RatioXY = 1.000000000000000000
      Caption = 'BGRAShape1'
      ExplicitLeft = 0
      ExplicitTop = 0
    end
  end
end
