object Form1: TForm1
  Left = 351
  Top = 80
  Caption = 'BCFilters'
  ClientHeight = 431
  ClientWidth = 763
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = True
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  PixelsPerInch = 96
  TextHeight = 13
  object ListBox1: TListBox
    Left = 258
    Top = 8
    Width = 120
    Height = 240
    ExtendedSelect = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ItemHeight = 13
    ParentFont = False
    TabOrder = 0
    OnClick = ListBox1Click
  end
  object ListBox2: TListBox
    Left = 384
    Top = 6
    Width = 120
    Height = 240
    ExtendedSelect = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ItemHeight = 13
    ParentFont = False
    TabOrder = 1
    OnClick = ListBox1Click
  end
  object ListBox3: TListBox
    Left = 510
    Top = 6
    Width = 120
    Height = 240
    ExtendedSelect = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ItemHeight = 13
    ParentFont = False
    TabOrder = 2
    OnClick = ListBox1Click
  end
  object ListBox4: TListBox
    Left = 636
    Top = 6
    Width = 120
    Height = 240
    ExtendedSelect = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ItemHeight = 13
    ParentFont = False
    TabOrder = 3
    OnClick = ListBox1Click
  end
  object TrackBar1: TTrackBar
    Left = 258
    Top = 258
    Width = 294
    Height = 36
    Max = 100
    Min = 1
    ParentShowHint = False
    Position = 100
    ShowHint = False
    TabOrder = 6
    OnChange = fs1Change
  end
  object TrackBar2: TTrackBar
    Left = 258
    Top = 306
    Width = 294
    Height = 36
    Max = 100
    Min = 1
    Position = 100
    TabOrder = 5
    OnChange = fs1Change
  end
  object TrackBar3: TTrackBar
    Left = 258
    Top = 348
    Width = 294
    Height = 36
    Max = 100
    Min = 1
    Position = 100
    TabOrder = 4
    OnChange = fs1Change
  end
  object TrackBar4: TTrackBar
    Left = 258
    Top = 384
    Width = 294
    Height = 36
    Max = 255
    Position = 255
    TabOrder = 7
    OnChange = fs1Change
  end
  object vs1: TBGRAVirtualScreen
    Left = 8
    Top = 8
    Width = 244
    Height = 244
    OnRedraw = vs1Redraw
    Alignment = taLeftJustify
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 8
  end
  object fs1: TCurrencyEdit
    Left = 24
    Top = 281
    Width = 121
    Height = 21
    Margins.Left = 4
    Margins.Top = 1
    DecimalPlaces = 5
    DisplayFormat = '0.00000'
    TabOrder = 9
    Value = 1.000000000000000000
    OnChange = fs1Change
  end
  object fs2: TCurrencyEdit
    Left = 24
    Top = 306
    Width = 121
    Height = 21
    Margins.Left = 4
    Margins.Top = 1
    DecimalPlaces = 5
    DisplayFormat = '0.00000'
    TabOrder = 10
    Value = 0.980000000000000000
    OnChange = fs2Change
  end
  object Timer1: TTimer
    Interval = 100
    OnTimer = Timer1Timer
    Left = 198
    Top = 54
  end
end
